// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCRB.DAL.EntityModel
{
    public partial class ConfigurationDetail
    {
        [Key]
        public Guid ID { get; set; }
        public Guid ConfigurationID { get; set; }
        [Required]
        [StringLength(100)]
        public string FieldName { get; set; }
        [Required]
        [StringLength(100)]
        public string Type { get; set; }
        public bool Required { get; set; }
        public int Length { get; set; }
        public int Len { get; set; }
        public int Des { get; set; }
        public int? Order { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Required]
        [StringLength(200)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [StringLength(200)]
        public string UpdateBy { get; set; }
        public bool? IsActive { get; set; }
    }
}