// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCRB.DAL.EntityModel
{
    public partial class ConfigurationMaster
    {
        [Key]
        public Guid ID { get; set; }
        [Required]
        [StringLength(200)]
        public string TemplateName { get; set; }
        public string InputFile { get; set; }
        [Required]
        public string OutputFile { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Required]
        [StringLength(200)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [StringLength(200)]
        public string UpdateBy { get; set; }
        public bool? IsActive { get; set; }
    }
}