// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TCRB.DAL.EntityModel
{
    public partial class ConfigurationDetail
    {
        public Guid ID { get; set; }
        public Guid ConfigurationID { get; set; }
        public string FieldName { get; set; }
        public string Type { get; set; }
        public bool Required { get; set; }
        public int Length { get; set; }
        public int Len { get; set; }
        public int Des { get; set; }
        public int? Order { get; set; }
        public DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool? IsActive { get; set; }
    }
}